spring:
  application:
    name: SWP_SE1941JV_GR2_PLS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pls
    username: root
    password: 21012005
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: seswp5069@gmail.com
    password: yblpwtdhqrucjtes
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  base-url: http://localhost:5555
server:
  port: 5555

logging:
  level:
    root: warn